platform :ios, '13.0'
inhibit_all_warnings!

#Debug tools
def import_debug
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'FLEX', :configurations => ['Debug']
    # pod 'MLeaksFinder', :configurations => ['Debug']
end

def import_JSONDecode
    pod 'Argo'
    pod 'Curry'
    pod 'Runes'
    pod 'HandyJSON'
end

def import_Rx
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
end

def import_Statistics
    pod 'Fabric'
    pod 'Crashlytics'
end

def import_Thoughtbot
    pod "Perform", :git => 'https://github.com/thoughtbot/Perform.git' 
    pod 'Delta', :git => "https://github.com/thoughtbot/Delta.git"
end

def import_SyntacticSugar
    pod 'Then'
end

target 'HiPDA' do
  use_frameworks!

  # Pods for HiPDA
  import_debug
  import_JSONDecode
  import_Rx
  import_Statistics
  import_Thoughtbot
  import_SyntacticSugar
  
  pod 'SAMKeychain'
  pod 'YYKeyboardManager'
  pod 'YYText', '~> 1.0.7', :inhibit_warnings => true
  pod 'YYImage', '~> 1.0.4'
  pod 'Moya/RxSwift'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'MBProgressHUD'
  pod 'SDWebImage/GIF'
  pod 'YYCache'
  pod 'MJRefresh'
  pod 'UITableView+FDTemplateLayoutCell' 
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  pod 'HTMLString' 
  #pod 'FDFullscreenPopGesture', '~> 1.1'
  #pod 'JZNavigationExtension', '~> 1.5.0.1'
  pod 'JSQMessagesViewController', '~> 7.3.4'
  pod 'AcknowList'
  
  target 'HiPDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiPDAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# For Xcode 11.0 & Swift 5.0
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
